import mongoose from "mongoose";
import { TERMS } from "./AcademicTerm.js";

// Emoji scale used by both child and teacher, mapped to a numeric score
// so we can compute a combined average automatically.
const EMOJI_SCORES = {
  "very_sad": 1,
  "sad": 2,
  "neutral": 3,
  "happy": 4,
  "very_happy": 5,
};

const emotionCheckinSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      required: true,
    },

    teacher: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Child's own emoji tap (self-report). Optional — the child and teacher
    // submit independently, so either one may arrive first for the day.
    childEmoji: {
      type: String,
      enum: Object.keys(EMOJI_SCORES),
    },

    // Teacher's independently observed emoji. Also optional for the same
    // reason.
    teacherEmoji: {
      type: String,
      enum: Object.keys(EMOJI_SCORES),
    },

    // Auto-calculated composite score (average of both, 1-5)
    compositeScore: {
      type: Number,
    },

    // Academic Year / Term this check-in belongs to. Manually chosen on
    // the teacher/admin-facing forms; auto-derived from today's date
    // against the configured AcademicTerm calendar when the child's own
    // one-tap self check-in creates the day's record first (see
    // studentController.submitChildEmotionCheckin) — kept optional since a
    // date outside any configured term shouldn't block the child's check-in.
    academicYear: {
      type: String,
      trim: true,
    },

    term: {
      type: String,
      enum: ["", ...TERMS],
      default: "",
    },

    sessionDate: {
      type: Date,
      default: Date.now,
    },

    // Was the child's self check-in submitted during the school day or
    // afterwards (e.g. from home in the evening)? Set automatically from
    // the server clock at submission time — not shown to the child, but
    // carried through to the activity-plan response so the "even after
    // school hours" suggestion flow can eventually feed this into the AI
    // step. Purely informational for now (no gating on it anywhere).
    context: {
      type: String,
      enum: ["school", "home"],
      default: "school",
    },

    // FR-09: the 3-activity plan (Aesthetic, Social, Academic) generated by
    // utils/aiActivityPlanEngine.js at the moment both sides of this
    // check-in were complete (or regenerated if the emojis are later
    // edited). Stored on the record itself — rather than only ever
    // recomputed from the latest check-in — so the Emotion Tracker
    // History table can show exactly what was suggested for *this*
    // specific past check-in, not just today's.
    activityPlan: {
      band: {
        type: String,
        enum: ["low", "steady", "positive"],
      },
      cards: [
        {
          _id: false,
          key: String,
          category: String,
          icon: String,
          title: String,
          color: String,
          description: String,
        },
      ],
      // "ai:<model>" when an NVIDIA model produced it, "rules-engine" when
      // every model call failed/timed out and the deterministic
      // utils/activityPlanEngine.js fallback was used instead.
      source: {
        type: String,
      },
      generatedAt: {
        type: Date,
      },
    },
  },
  {
    timestamps: true,
  }
);

// Automatically compute the composite score before saving. If only one
// side (child or teacher) has checked in so far, the score is just that
// one value — it's recalculated as an average once both are present.
emotionCheckinSchema.pre("save", function () {
  const childScore = this.childEmoji ? EMOJI_SCORES[this.childEmoji] : null;
  const teacherScore = this.teacherEmoji
    ? EMOJI_SCORES[this.teacherEmoji]
    : null;

  if (childScore !== null && teacherScore !== null) {
    this.compositeScore = Number(((childScore + teacherScore) / 2).toFixed(1));
  } else if (childScore !== null) {
    this.compositeScore = childScore;
  } else if (teacherScore !== null) {
    this.compositeScore = teacherScore;
  }
});

const EmotionCheckin = mongoose.model("EmotionCheckin", emotionCheckinSchema);

export default EmotionCheckin;
export { EMOJI_SCORES };